### ISSUE TITLE
Trailing whitespaces in configurations should be filtered

### ISSUE THREAD

**Issue by cs-1** [napalm-automation-community/napalm-aos#12]
Due to some strange reason, AOS 8 has trailing whitespaces in configuration lines. This makes merging configuration files difficult. In my eyes napalm-aos should always filter trailing whitespaces present in the running configuration when merging configurations. This makes writing templates much easier.

**Comment by vmuthukrishnan** [comment]
I am working with the SW Team to address this concern. Could you let me know the exact 7x and 8x version used and the respective platforms?

**Comment by cs-1** [comment]
The AOS 7 devices are OS6900-X40 and -X20 w/ AOS 7.3.4.273.R02, and the AOS 8 devices are OS6560-P48Z16 w/ AOS 8.4.1.141.R03 GA. Please note that this is nothing new. AOS 6 devices also had the exact same strangeness. There're whitespaces in places of the configuration where they make no sense at all (at the end of a line or several ones in between keywords in a single line). It drives you nuts if you do automatic configuration management. In my eyes the only correct way to fix this would be to fix AOS to remove all superfluous whitespaces.

**Comment by napalmaos** [comment]
Hi, 
Please help to test again.
If it doesn't work with you, please help to share your *.yml file and output.
Thanks,

**Comment by cs-1** [comment]
Hi, the patch works, thanks!
