### ISSUE TITLE
Candidate configuration files are never deleted from the switch

### ISSUE THREAD

**Issue by cs-1** [napalm-automation-community/napalm-aos#14]
When merging or replacing a configuration on a switch, the candidate configuration file in the switch's "/flash" filesystem is never deleted. Also, "/flash/napalm" is never deleted.

**Comment by napalmaos** [comment]
Please help to test this issues again.
Thanks

**Comment by napalmaos** [comment]
Please close an issue if it was resolve.
Thanks

**Comment by vmuthukrishnan** [comment]
Hi, Kindly close the issue if it is resolved, otherwise let us know if there any issues still present.
