### ISSUE TITLE
compatibility with napalm-ansible

### ISSUE THREAD

**Issue by shibumi** [napalm-automation-community/napalm-aos#2]
Heyho,
We are currently testing NAPALM for our environment. I would like to ask if this project is compatible with napalm-ansible? If so can you add an installation guide to the README? We have installed napalm, napalm-ansible and napalm-aos. (napalm and napalm-aos via pip) (napalm-ansible via git clone).
Ansible can execute the napalm module, but seems like ansible can't find the drivers for napalm-aos.

**Comment by vmuthukrishnan** [comment]
We have tested with ansible and it is working. Let us know if you are facing any issue.

**Comment by vmuthukrishnan** [comment]
Is the issue resolved? If so, could you close the ticket?

**Comment by cs-1** [comment]
This issue is resolved with the current napalm-ansible dev branch.
