### ISSUE TITLE
get_vlans() method and test getter not present (Napalm < 3.0)

### ISSUE THREAD

**Issue by jefvantongerloo** [napalm-automation-community/napalm-aos#35]
**Reference pull request**
Add Napalm get_vlans() method #34

****Dependent pull request (solution)**
 Make compatible with Napalm 3 #30 

**Issue**
- get_vlans method not available in Napalm base 2.3.1
```
def get_vlans(self):
        """
        Return structure being spit balled is as follows.
            * vlan_id (int)
                * name (text_type)
                * interfaces (list)

        Example::

            {
                1: {
                    "name": "default",
                    "interfaces": ["GigabitEthernet0/0/1", "GigabitEthernet0/0/2"]
                },
                2: {
                    "name": "vlan2",
                    "interfaces": []
                }
            }
        """
        raise NotImplementedError
```

- get_vlans test case not present in Napalm 2.3.1
```
    @wrap_test_cases
    def test_get_vlans(self, test_case):
        """Test get_vlans."""
        get_vlans = self.device.get_vlans()

        assert len(get_vlans) > 0

        for vlan, vlan_data in get_vlans.items():
            assert helpers.test_model(models.vlan, vlan_data)

        return get_vlans
```

**Tests**
get_vlans() tested and confirmed working in Napalm versions: 
- 2.3.1
- 3.0 (Napalm-aos from PR #30)
- 3.2 (Napalm-aos from PR #30)

**Comment by napalmaos** [comment]
Updated the code please help to retest

**Comment by jefvantongerloo** [comment]
Why did you copy paste code instead of merging this PR?

**Comment by napalmaos** [comment]
Thank for your contribution,

Actually, we create the changes with others for testing with our setup, We need to test on all devices platform,

Sorry for inconvenience,

**Comment by jefvantongerloo** [comment]
You could pull this PR test and commit your own additions to the fork or test in CI/CD.
Afterwards you can merge the PR.

How is this suppose to be an open-source project where people contribute to improve the napalm-aos library when you just copy paste code. Nevertheless thank you for the Napalm 3.0 compatibility upgrade.
