### ISSUE TITLE
Relative paths in tasks don't work

### ISSUE THREAD

**Issue by cs-1** [napalm-automation-community/napalm-aos#9]
When using relative paths for things like "config_file" or "diff_file" in the napalm_install_config task, the files aren't found. Only when using the absolute path it starts working. Relative paths from the Ansible main directory should definitely work so that yml configs don't grow too big.

**Comment by napalmaos** [comment]
hi,

Are you using python 3?
Relative paths works normally with python 2. This may be a ansible's issue with python 3.

Thanks.

**Comment by cs-1** [comment]
Yes, I use Python 3. If this is indeed an upstream problem, I'll close this issue. Thanks for pointing out that this is a Python 2/3 problem.
